### ISSUE TITLE
Problem while loading a repository

### ISSUE THREAD

**Issue by tkowalczyk** [Gitential-com/feedback#13]
Screen below:

![image](https://user-images.githubusercontent.com/1682564/40677537-3fc37d2c-637e-11e8-9857-aa7ff2981eea.png)

**Comment by peresztegi** [comment]
Hey Thomasz,

[First things first: polak węgier dwa bratanki i do szabli i do szklanki] :D

Thanks for your feedback, we are aware of the issue and are working on fixing it. We are experiencing increased usage and are in the process of upgrading our systems, so please bear with us for a couple of hours and everything should be back to normal soon. We'll comment on this issue again and close it once we're back online - should be in the morning CEST time.

Zoltan

**Comment by tkowalczyk** [comment]
@peresztegi Dziękuje! ;)

**Comment by tkowalczyk** [comment]
Any info when your project will be available?

**Comment by peresztegi** [comment]
Apologies for this, we're back online - we've ran into some unexpected issues and have been back up since we messaged back-and-forth here, but most importantly, we're up and running! Thanks for your patience and support!
