### ISSUE TITLE
Unmerge authors

### ISSUE THREAD

**Issue by atchertchian** [Gitential-com/feedback#3]
Hi,

I could not figure out how to "unmerge" authors from the "Deduplicate git authors" menu: one user is actually gathering emails from 3 other users, how can i separate them?

Thanks

**Comment by kszucs** [comment]
Hi @atchertchian!

Thanks for the report! I'm currently on vacation until thursday, but we'll do this in our next sprint.
cc @tdna

**Comment by tdna** [comment]
Hi!

If you'd like to move email to another name you can do it by texting into "Add new email" input.
But unfortunately there is no option to create new names yet.
We are planning to do this soon.
How important is that for you?
Until if it is a small change we can do it manually in our database

**Comment by atchertchian** [comment]
Hi,

I tried to "remove" some users by emptying their email address, gathering all "old" email addresses on one given user for instance, to make our list shorter, but the user remained without any emails addresses (but that is a slightly different subject).

About the "manual unmerge", it would be cool if you could do this manually on your end for now, because we're seeing merged activity for several distinct authors with a very different activity.

I will send you detailed information by email, thanks!

**Comment by atchertchian** [comment]
(sent an email to @kszucs)

**Comment by tdna** [comment]
We separated those authors manually.
Please check if the current state is right for you.
If you need any other help please let us know.
Thanks

**Comment by atchertchian** [comment]
State looks alright, many thanks!

**Comment by kszucs** [comment]
Closing, thanks Anahide!

**Comment by atchertchian** [comment]
Hey,
I'm still interested in a way to do that on my end though (i'd like to merge two authors in current state, for instance), is this feature now available?
Thanks

**Comment by tdna** [comment]
@atchertchian could you please try now Git Authors page?
Now there is an option to delete or add authors.

**Comment by atchertchian** [comment]
Sorry for the delay, looks good! Many thanks!
